"""solvent_data.py — données de référence pour parse_solvent.py.

Contient uniquement des données (whitelist, synonymes, mots-clés de bruit,
préfixes de méthode) : aucune logique de parsing ici.
"""

# ── WHITELIST ─────────────────────────────────────────────────────────────────
# Formes canoniques (minuscules). Seuls ces noms apparaissent dans solvent_clean.
# Ajouter ici chaque nouveau solvant validé.
WHITELIST = {
    'acetone',
    'acetonitrile',
    'butyl acetate',
    't-butyl acetate',
    '1-butanol',
    '1-chlorobutane',
    '1-chloropentane',
    'dichloropentane',
    '2-chlorobutane',
    'chlorobenzene',
    'chloroform',
    'cyclohexane',
    'cyclopentane',
    '1,2-dichlorobenzene',
    '1,3-dichlorobenzene',
    '1,4-dichlorobenzene',
    'dichloromethane',
    'dimethylacetamide',
    'n-methylacetamide',
    'dimethyl sulfoxide',
    '1,4-dioxane',
    'dimethylformamide',
    'ethyl acetate',
    'ethanol',
    'dimethyl ether',
    'methyl ethyl ether',
    'diethyl ether',
    '1,2-dichloroethane',
    '1,3-dichloropropane',
    'heptane',
    'hexane',
    'isooctane',
    '2-propanol',
    'isopropyl myristate',
    'methanol',
    'methyl t-butyl ether',
    '2-butanone',
    'methyl isoamyl ketone',
    'methyl isobutyl ketone',
    '2-pentanone',
    'n-methylpyrrolidone',
    'n-ethylpyrrolidone',
    '2-pyrrolidone',
    'pentane',
    '1-propanol',
    'propylene carbonate',
    'pyridine',
    'tetrahydrofuran',
    'toluene',
    '1,2,4-trichlorobenzene',
    '1,1,2-trichlorotrifluoroethane',
    'trifluoroacetic acid',
    'trichloroacetic acid',
    'triethylamine',
    'water',
    'o-xylene',
    'benzene',
    'petroleum ether',
    'chloroform-d',
    'dichloromethane-d2',
    'nitromethane',
    'nitroethane',
    'methyl nitrate',
    '1-nitropropane',
    '2-nitropropane',
    'hydrochloric acid',
    'hydrobromic acid',
    'hydroiodic acid',
    'hydrofluoric acid',
    'sulfuric acid',
    'nitric acid',
    'phosphoric acid',
    'perchloric acid',
    'acetic acid',
    'p-toluenesulfonic acid',
    'm-toluenesulfonic acid',
    'methanesulfonic acid',
    'trifluoromethanesulfonic acid',
    'hypophosphorous acid',
    'ammonia',
    'acetic anhydride',
    'diethylformamide',
    'n,n-diphenylformamide',
    'n-methyl-n-phenylformamide',
    'n,n-dimethylthioformamide',
    'dimethylformamide-d7',
    '2-methylpyridine',
    '3-methylpyridine',
    '4-methylpyridine',
    '2-cyanopyridine',
    '3-cyanopyridine',
    '4-cyanopyridine',
    '2,3-lutidine',
    '2,4-lutidine',
    '2,5-lutidine',
    '2,6-lutidine',
    '3,4-lutidine',
    '3,5-lutidine',
    'collidine',
    'quinoline',
    'pyrazine',
    'pyrimidine',
    'pyridazine',
    'imidazole',
    '1-methylimidazole',
    '2-methylimidazole',
    'piperidine',
    'pyrrole',
    'thiophene',
    'pyrrolidine',
    'morpholine',
    'aniline',
    'n,n-dimethylaniline',
    'n-methylaniline',
    'methylamine',
    'ethylamine',
    'dimethylamine',
    'diethylamine',
    'isopropylamine',
    'n-propylamine',
    'butylamine',
    'dibenzylamine',
    'benzylamine',
    'tributylamine',
    'trimethylamine',
    'hexafluorobenzene',
    'pentafluorobenzene',
    'pentafluoropyridine',
    'tetrafluoropyridine',
    '1,2,3,4-tetrafluorobenzene',
    '1,2,3,5-tetrafluorobenzene',
    '1,2,4,5-tetrafluorobenzene',
    '1,2,3-trifluorobenzene',
    '1,2,4-trifluorobenzene',
    '1,3,5-trifluorobenzene',
    'perfluorotoluene',
    'trifluoromethylbenzene',
    '1,3-bis(trifluoromethyl)benzene',
    '2,2,2-trifluoroethanol',
    'hexafluoroisopropanol',
    'perfluorohexane',
    'perfluoropentane',
    'hexafluoropentane',
    'perfluorocyclohexane',
    'perfluoromethylcyclohexane',
    't-butylbenzene',
    '1,3,5-tri-t-butylbenzene',
    '5-tert-butyl-m-xylene',
    'cumene',
    'indane',
    'tetralin',
    'decalin',
    'isoamyl alcohol',
    '3-pentanone',
    '3-methyl-2-butanone',
    '4-heptanone',
    '2-nonanone',
    'cyclohexanone',
    '2-methylcyclohexanone',
    '3-methylcyclohexanone',
    '4-methylcyclohexanone',
    'cyclopentanone',
    'cycloheptanone',
    'cyclooctanone',
    'isophorone',
    '2-bromotoluene',
    '3-bromotoluene',
    '4-bromotoluene',
    'cyclohexene',
    'cyclooctene',
    'cyclopentene',
    'norbornene',
    'cyclopentene oxide',
    'cyclohexene oxide',
    '2-bromoanisole',
    '1-bromo-3-methoxybenzene',
    '1-bromo-4-methoxybenzene',
    'propylene oxide',
    'cycloheptane',
    'cyclooctane',
    'nonane',
    'decane',
    'undecane',
    'dodecane',
    'tetradecane',
    'hexadecane',
    '2-methylbutane',
    '2-methylpentane',
    '2,2,3-trimethylbutane',
    'neopentane',
    'methyl benzoate',
    'ethyl benzoate',
    'isobutyl benzoate',
    'isobutyl acetate',
    'methyl acetoacetate',
    'methyl pyruvate',
    'benzyl benzoate',
    'methyl acetate',
    'methyl formate',
    'methyl acrylate',
    'ethyl acrylate',
    'acrylic acid',
    'methyl methacrylate',
    'formyl acetoacetate',
    'n-butyl acrylate',
    'propyl acetate',
    'isopropyl acetate',
    'pentyl acetate',
    'ethyl formate',
    'vinyl acetate',
    'ethyl lactate',
    'ethyl propanoate',
    'diethyl carbonate',
    'ethylene carbonate',
    'anisole',
    'phenetole',
    'diphenyl ether',
    'dibutyl ether',
    'dipropyl ether',
    'cyclopentyl methyl ether',
    'dimethyl carbonate',
    'diethylene glycol',
    'triethylene glycol',
    'tetraethylene glycol',
    '1,4-anhydroerythritol',
    'hexylene glycol',
    'propylene glycol',
    'glycerol',
    'tetramethylurea',
    'tetraethylurea',
    'urea',
    'hexamethylphosphoramide',
    'sulfolane',
    'tetramethylsilane',
    'hexamethyldisilane',
    't-butylamine',
    'tetramethylethylenediamine',
    'pentamethyldiethylenetriamine',
    'diethylzinc',
    'mineral oil',
    'silicone oil',
    'limonene',
    'd-limonene',
    'carvone',
    'alpha-pinene',
    'beta-pinene',
    '2-morpholinoethanol',
    'paraffin oil',
    'fluorinert',
    'methyl perfluorobutyl ether',
    'pentachloroethane',
    'hexachloroethane',
    '1,1,2,2-tetrachloroethane',
    '1,1,1,2-tetrafluoroethane',
    '1,1,2-trichloroethane',
    '1,1,1-trichloroethane',
    'trichloroethylene',
    'tetrachloroethylene',
    'dichloroethylene',
    '1,2-dichloroethylene',
    'cis-1,2-dichloroethylene',
    'trans-1,2-dichloroethylene',
    '1,2,3-trichlorobenzene',
    '1,3,5-trichlorobenzene',
    'bromobenzene',
    '1,2-dibromobenzene',
    '1,3-dibromobenzene',
    '1,4-dibromobenzene',
    'iodobenzene',
    '1-bromodecane',
    '1,8-dibromooctane',
    '1-bromobutane',
    '1-bromopropane',
    '2-bromobutane',
    'iodoethane',
    'iodomethane',
    'diiodomethane',
    'bromoform',
    'chlorine',
    'cyanogen chloride',
    'chloromethane',
    'chlorocyclohexane',
    '2-chloro-2-methylpropane',
    'trichlorofluoromethane',
    'dichlorofluoromethane',
    'chlorodifluoromethane',
    'chlorotrifluoromethane',
    'difluoromethane',
    '1,2,3-trichloropropane',
    'triethylorthoformate',
    'trimethylorthoformate',
    'diethyl oxalate',
    'diethyl malonate',
    'dimethyl sulfate',
    'thionyl chloride',
    'vanadium tetrachloride',
    'sulfuryl chloride',
    'sulfuryl chloride fluoride',
    'acetyl chloride',
    'antimony pentachloride',
    'antimony trichloride',
    'antimony pentafluoride',
    'antimony trifluoride',
    'titanium tetrachloride',
    'boron trifluoride',
    'ammonium hexafluorophosphate',
    'phosphorus oxychloride',
    'sulfuryl fluoride',
    'sulfur tetrafluoride',
    'sulfur dioxide',
    'liquid sulfur dioxide',
    'nitrogen',
    'carbon dioxide',
    'hydrogen',
    'hydrogen peroxide',
    'iodine',
    'bromine',
    '1-chloronaphthalene',
    '2-chloronaphthalene',
    'naphthalene',
    'biphenyl',
    'diphenylmethane',
    '2-chlorotoluene',
    '3-chlorotoluene',
    '4-chlorotoluene',
    'ethylbenzene',
    'propylbenzene',
    'diisopropylbenzene',
    'butylbenzene',
    'isobutylbenzene',
    '1-hexene',
    '2,3-dimethyl-1,3-butadiene',
    '1,3-butadiene',
    '1,4-pentadiene',
    'trans-stilbene',
    'cis-stilbene',
    'stilbene',
    'styrene',
    'allylbenzene',
    '1,3-diphenylpropane',
    'dibenzofuran',
    'isoquinoline',
    'fluorene',
    '1,2-dimethoxybenzene',
    '1,3-dimethoxybenzene',
    '1,4-dimethoxybenzene',
    '4-methylanisole',
    '2-methylanisole',
    '3-methylanisole',
    '2-nitroanisole',
    '4-nitroanisole',
    'anthracene',
    'diboraanthracene',
    'pyrene',
    '1-methylnaphthalene',
    '2-methylnaphthalene',
    'nitrobenzene',
    'ethane',
    'butane',
    'propane',
    'isobutane',
    'cyclobutane',
    'cyclobutanone',
    '2,2-dimethylbutane',
    'cyclopropane',
    '2-butanol',
    't-butanol',
    'isobutanol',
    '2-methylbutan-2-ol',
    '2-methyl-1-butanol',
    '2-methylprop-2-en-1-ol',
    '1-pentanol',
    '2-pentanol',
    '3-pentanol',
    '1-hexanol',
    '1-heptanol',
    '1-octanol',
    '1-decanol',
    '2-ethylhexanol',
    'benzyl alcohol',
    'phenol',
    'o-cresol',
    'm-cresol',
    'p-cresol',
    'cyclohexanol',
    'furfuryl alcohol',
    'diacetone alcohol',
    'ethanolamine',
    'diethanolamine',
    'triethanolamine',
    'hydroxylamine',
    'hydrazine',
    '2-ethoxyethanol',
    '2-chloroethanol',
    '2-ethoxyethyl acetate',
    '2-methoxyethyl acetate',
    'diethylene glycol monoethyl ether',
    'diethylene glycol monomethyl ether',
    '1,3-propanediol',
    '1,4-butanediol',
    'methanol-d4',
    'ethanol-d6',
    'acetone-d6',
    'acetonitrile-d3',
    'dimethyl sulfoxide-d6',
    'toluene-d8',
    'tetrahydrofuran-d8',
    'pyridine-d5',
    'water-d2',
    'benzene-d6',
    'ethylenediamine',
    'carbon tetrachloride',
    'octane',
    'fluorobenzene',
    '1,2,3,4-tetramethylbenzene',
    '1,2,3,5-tetramethylbenzene',
    '1,2,4,5-tetramethylbenzene',
    '1,2,4-trimethylbenzene',
    'm-xylene',
    'p-xylene',
    'xylene',
    'hexamethyldisiloxane',
    'hexamethyldisilazane',
    '1,2-difluorobenzene',
    '1,3-difluorobenzene',
    '1,4-difluorobenzene',
    'benzonitrile',
    'acetophenone',
    'benzophenone',
    'ethylene glycol',
    '2-methoxyethanol',
    'diglyme',
    'tetraglyme',
    'gamma-butyrolactone',
    'formamide',
    'formic acid',
    'acetaldehyde',
    'formaldehyde',
    'benzaldehyde',
    'acetylacetone',
    'propionic acid',
    'butyric acid',
    'decanoic acid',
    'heptanoic acid',
    'octanoic acid',
    'hexanoic acid',
    'valeric acid',
    'pivalic acid',
    'oxalic acid',
    'carbon disulfide',
    'dibromomethane',
    'bromochloromethane',
    'methylcyclohexane',
    'ethylcyclohexane',
    'methylcyclopentane',
    'cis-1,2-dimethylcyclohexane',
    'trans-1,2-dimethylcyclohexane',
    '1,2-dimethylcyclohexane',
    '1,3-dimethylcyclohexane',
    '1,4-dimethylcyclohexane',
    'propionitrile',
    'butyronitrile',
    'isobutyronitrile',
    't-butyl isonitrile',
    'phenyl isonitrile',
    'hexanedinitrile',
    'methacrylonitrile',
    'acrylonitrile',
    'trichloroacetonitrile',
    'chloroacetonitrile',
    'trimethylacetonitrile',
    'phenylacetonitrile',
    'mesitylene',
    'dimethoxyethane',
    'tetrahydropyran',
    '2-methyltetrahydrofuran',
    'furan',
    'dimethoxymethane',
    'tetrahydrothiophene',
    '1,3-dioxolane',
    'diisopropyl ether',
    'ethyl isopropyl ether',
    'polyethylene glycol',
    'polypropylene glycol',
    'n-methylformamide',
    'di-t-butyl ether',
    '3-methoxypropionitrile',
    'cyrene',
    '1,3-dimethylimidazolidin-2-one',
    '2,2-dimethoxypropane',
    '1,3-dimethoxypropane',
    'ionic liquid',
    'methyl propargyl ether',
    '2,3-dihydrofuran',
    'acetamide',
    'methyl pivalate',
    '2-methyl-2-butene',
    'tert-butylethylene',
    'dmpu',
    'n-ethylpyrrolidone',
    'tetraethylurea',
    '2-methylbenzyl alcohol',
    '3-nitrobenzyl alcohol',
    '4-nitrobenzyl alcohol',
    '2-nitrobenzyl alcohol',
    '2-hexanone',
    '3,3-dimethyl-2-butanone',
    '2-butyne',
    '2-nitrotoluene',
    'cinnamaldehyde',
    'cycloocta-1,5-diene',
    '4-methyltetrahydropyran',
    '3-nitrotoluene',
    '4-nitrotoluene',
    'diethyl sulfide',
    'dimethyl sulfide',
    'diethyl sulfoxide',
    'ethyl-isopropylsulfoxide',
    'ethyl-methylsulfoxide',
    '1,2-dimethoxypropane',
    'allylamine',
    '2-iodotoluene',
    '3-iodotoluene',
    '4-iodotoluene',
    'benzoic acid',
    '2,2,5-trimethylpentane',
    'isochromane',
    'dibenzyl ether',
    'eucalyptol',
    '3-carene',
    'dihydrocarvone',
    'ethyl benzoylacetate',
    'diethyl suberate',
    'cycloheptene',
    'trifluoromethane',
    'xylenol',
    '2,5-dimethoxytetrahydrofuran',
    'methyl propionate',
    '1,4-oxathiane',
    '1-aminopropan-2-ol',
    'methylethylbenzene',
    'hexafluorophosphoric acid',
    '1,2-dibromoethane',
    'n-formylpiperidine',
}

# ── SYNONYMES ─────────────────────────────────────────────────────────────────
# Regroupes par solvant canonique (cible dans WHITELIST) plutot qu'en un seul
# dict plat : un meme synonyme ne peut alors pointer que vers UN seul canonique,
# et toute incoherence (cle ajoutee sous deux canoniques differents) leve une
# erreur explicite au chargement plutot que d'ecraser silencieusement.
SYNONYM_GROUPS = {
    '1,1,1-trichloroethane': [
        'trichloroethane',
        'methylchloroform',
    ],
    '1,1,2,2-tetrachloroethane': [
        'tetrachloroethane',
        'cl2chchcl2',
        'sym-tetrachloroethane',
        'as-tetrachloroethane',
        '1,1,2,2-tetrachloro-1,2-dideuteroethane',
    ],
    '1,1,2-trichlorotrifluoroethane': [
        '1,1,2-trifluorotrichloroethane',
        'freon 113',
        'freon-113',
        '1,1,2-trichloro-1,2,2-trifluoroethane',
    ],
    '1,2,3,4-tetrafluorobenzene': [
        'tetrafluorobenzene',
    ],
    '1,2,3-trichlorobenzene': [
        'trichlorobenzene',
    ],
    '1,2,4,5-tetramethylbenzene': [
        'durene',
    ],
    '1,2,4-trichlorobenzene': [
        ',2,4-trichlorobenzene',
    ],
    '1,2,4-trifluorobenzene': [
        'trifluorobenzene',
    ],
    '1,2,4-trimethylbenzene': [
        'pseudocumene',
    ],
    '1,2-dichlorobenzene': [
        'o-dichlorobenzene',
        'ortho-dichlorobenzene',
        'o-dcb',
        'odcb',
        'dichlorobenzene',
        '1,2-dicholobenzene',
        'o-diclorobenzene',
    ],
    '1,2-dichloroethane': [
        'ethylene dichloride',
        'dce',
        'c2h4cl2',
        'dichloroethane',
        'edc',
        '1,2-dce',
    ],
    '1,2-dichloroethylene': [
        '1,2-dichloroethene',
    ],
    '1,2-difluorobenzene': [
        'diflurobenzene',
        'c6h4f2',
        'o-difluorobenzene',
        'ortho-difluorobenzene',
        '1,2-di-fluorobenzene',
        'o-dfb',
        'odfb',
        'difluorobenzene',
        '1,2.difluorobenzene',
    ],
    '1,2-dimethoxybenzene': [
        '1.2-dimethoxybenzene',
        'dimethoxybezene',
        'dimethoxybenzene',
        'veratrole',
    ],
    '1,2-dimethoxypropane': [
        'propylene glycol dimethyl ether',
        'pgdme',
    ],
    '1,3,5-trichlorobenzene': [
        '1,3,5-triochlorobenzene',
    ],
    '1,3-butadiene': [
        'butadiene',
        '1,2-butadiene',
    ],
    '1,3-dichlorobenzene': [
        'm-dichlorobenzene',
        'm-diclorobenzene',
    ],
    '1,3-difluorobenzene': [
        'm-difluorobenzene',
        '1,3-di-fluorobenzene',
        'meta-difluorobenzene',
        '1,3.difluorobenzene',
    ],
    '1,3-dimethoxybenzene': [
        '1.3-dimethoxybenzene',
    ],
    '1,3-dimethylimidazolidin-2-one': [
        '1,3-dimethyl-2-imidazolidinone',
        'dmeu',
        '1,3-dimethylethyleneurea',
    ],
    '1,3-dioxolane': [
        'dioxolane',
    ],
    '1,4-butanediol': [
        'butandiol',
    ],
    '1,4-dichlorobenzene': [
        'p-dichlorobenzene',
        'p-diclorobenzene',
    ],
    '1,4-difluorobenzene': [
        'p-difluorobenzene',
        '1,4-di-fluorobenzene',
        'para-difluorobenzene',
        '1,4.difluorobenzene',
    ],
    '1,4-dimethoxybenzene': [
        '1.4-dimethoxybenzene',
    ],
    '1,4-dioxane': [
        'dioxane',
        'p-dioxane',
        'dioxan',
        'dioxane mixture',
        'para-dioxane',
    ],
    '1,4-oxathiane': [
        '1,4-thioxane',
    ],
    '1,8-dibromooctane': [
        'dibromooctane',
        '1,8-dibromo-octane',
    ],
    '1-bromo-3-methoxybenzene': [
        '3-bromoanisole',
    ],
    '1-bromo-4-methoxybenzene': [
        '4-bromoanisole',
    ],
    '1-bromobutane': [
        'butyl bromide',
        'n-butyl bromide',
    ],
    '1-bromopropane': [
        'n-propyl bromide',
        'propyl bromide',
    ],
    '1-butanol': [
        'n-butanol',
        'n-butyl alcohol',
        'butyl alcohol',
        'butanol',
        'butan-1-ol',
    ],
    '1-chlorobutane': [
        'chlorobutane',
        'n-butyl chloride',
        'butyl chloride',
    ],
    '1-chloronaphthalene': [
        'chloronaphthalene',
    ],
    '1-decanol': [
        'decanol',
        'n-decanol',
    ],
    '1-heptanol': [
        'heptanol',
        'n-heptanol',
    ],
    '1-hexanol': [
        'hexanol',
        'n-hexanol',
    ],
    '1-hexene': [
        'hexene',
    ],
    '1-methylimidazole': [
        'n-methylimidazole',
        'nmim',
        'n-methylimidzole',
        'n-methylimidzaole',
    ],
    '1-nitropropane': [
        'nitropropane',
    ],
    '1-octanol': [
        'octanol',
        'n-octanol',
    ],
    '1-pentanol': [
        'n-pentanol',
        'n-amyl alcohol',
        'amyl alcohol',
        'pentan-1-ol',
        'pentanol',
    ],
    '1-propanol': [
        'n-propanol',
        'n-propyl alcohol',
        'propanol',
        'propan-1-ol',
    ],
    '2,2,2-trifluoroethanol': [
        'trifluoromethanol',
        '2,2,2-trifluoro / ethanol',
        '2,2,2-trifluoro/ethanol',
        'trifluoroethanol',
    ],
    '2,2-dimethoxypropane': [
        'dimethoxypropane',
        '1,1-dimethoxypropane',
    ],
    '2,2-dimethylbutane': [
        'neohexane',
    ],
    '2,3-lutidine': [
        '2,3-dimethylpyridine',
    ],
    '2,4-lutidine': [
        '2,4-dimethylpyridine',
    ],
    '2,5-lutidine': [
        '2,5-dimethylpyridine',
    ],
    '2,6-lutidine': [
        '2,6-dimethylpyridine',
    ],
    '2-bromoanisole': [
        '1-bromo-2-methoxybenzene',
    ],
    '2-butanol': [
        'sec-butanol',
        's-butanol',
        'butan-2-ol',
        'sec-butyl alcohol',
    ],
    '2-butanone': [
        'buta-2-one',
        'but-2-one',
        'methyl ethyl ketone',
        'ethyl methyl ketone',
        'ethyl methylketone',
        'methyl ethylketone',
        'mek',
        'butan-2-one',
        'butan-1-one',
        'butanone',
        'butanone-2',
        'ethylmethylketone',
        'methylethyl ketone',
        'methylethylketone',
    ],
    '2-chlorobutane': [
        's-butyl chloride',
    ],
    '2-chlorotoluene': [
        'ortho-chlorotoluene',
    ],
    '2-cyanopyridine': [
        'o-cyanopyridine',
        '2-cyano pyridine',
    ],
    '2-hexanone': [
        'hexanone',
    ],
    '2-methoxyethanol': [
        '2-methoxyethane',
        'methyl cellosolve',
        'methyl glycol',
        '2-methoxy-ethanol',
    ],
    '2-methyl-1-butanol': [
        '2-methylbutanol',
    ],
    '2-methylanisole': [
        '1-methoxy-2-methylbenzene',
    ],
    '2-methylbenzyl alcohol': [
        '2-methylbenzoylalcohol',
    ],
    '2-methylbutan-2-ol': [
        '2-methyl-2-butanol',
        'methyl t-butanol',
        'tert-amyl alcohol',
    ],
    '2-methylbutane': [
        'isopentane',
        'iso-pentane',
    ],
    '2-methylpyridine': [
        '2-picoline',
        'alpha-picoline',
        'alpha picoline',
        'α-picoline',
    ],
    '2-methyltetrahydrofuran': [
        '2me-tetrahydrofuran',
        '2-methyloxolane',
        '2-me-thf',
        '2mthf',
        '2-methyl tetrahydrofuran',
        '2-mthf',
        '(rac)-2-methyltetrahydrofuran',
    ],
    '2-nitrotoluene': [
        'nitrotoluene',
        'o-nitrotoluene',
    ],
    '2-nonanone': [
        'nonan-2-one',
    ],
    '2-pentanol': [
        'sec-amyl alcohol',
        'pentan-2-ol',
    ],
    '2-pentanone': [
        'methyl n-propyl ketone',
        'mpk',
        'pentan-2-one',
    ],
    '2-propanol': [
        'isopropyl alcohol',
        'isopropyl alcholol',
        'isoproponal',
        'isopropanol',
        'di-isopropanol',
        'i-propanol',
        'iso-propanol',
        'propan-2-ol',
        'ipa',
        'isopropanole',
        '2-propyl alcohol',
        'isopropol',
        'i-proh',
        'iproh',
        'isopropyl',
        'isopropyl alcoho',
    ],
    '3,3-dimethyl-2-butanone': [
        'pinacolone',
        'methyl tert-butyl ketone',
    ],
    '3,4-lutidine': [
        '3,4-dimethylpyridine',
    ],
    '3,5-lutidine': [
        '3,5-dimethylpyridine',
    ],
    '3-chlorotoluene': [
        'meta-chlorotoluene',
    ],
    '3-cyanopyridine': [
        'm-cyanopyridine',
        '3-cyano pyridine',
    ],
    '3-methyl-2-butanone': [
        'methyl isopropyl ketone',
        'mipk',
    ],
    '3-methylanisole': [
        '1-methoxy-3-methylbenzene',
    ],
    '3-methylpyridine': [
        '3-picoline',
        'beta-picoline',
        'beta picoline',
        'β-picoline',
    ],
    '3-nitrotoluene': [
        'm-nitrotoluene',
    ],
    '3-pentanone': [
        'diethyl ketone',
        'pentan-3-one',
    ],
    '4-bromotoluene': [
        '1-bromo-4-methylbenzene',
    ],
    '4-chlorotoluene': [
        'para-chlorotoluene',
    ],
    '4-cyanopyridine': [
        'p-cyanopyridine',
        '4-cyano pyridine',
    ],
    '4-methylanisole': [
        '1-methoxy-4-methylbenzene',
    ],
    '4-methylpyridine': [
        '4-picoline',
        'gamma-picoline',
        'gamma picoline',
        'γ-picoline',
    ],
    '4-methyltetrahydropyran': [
        '4-mthp',
    ],
    '4-nitrotoluene': [
        'p-nitrotoluene',
    ],
    '5-tert-butyl-m-xylene': [
        '5-t-butyl-m-xylen',
        '5-t-butyl-m-xylene',
    ],
    'acetic acid': [
        'ethanoic acid',
        'glacial acetic acid',
        'hac',
    ],
    'acetic anhydride': [
        'acetic acid anhydride',
    ],
    'acetone': [
        'propanone',
        '2-propanone',
        'aceton',
        'actone',
        'acetong',
    ],
    'acetone-d6': [
        'perdeuteroacetone',
        'perdeutroacetone',
        'deuteroacetone',
        'd6-acetone',
        'hexadeuteroacetone',
    ],
    'acetonitrile': [
        'mecn',
        'ch3cn',
        'ncme',
        'acn',
        'ethanenitrile',
        'methyl cyanide',
        'cetonitrile',
        'acetontrile',
        'acetonirile',
        'acetonitirle',
        'acetnitrile',
        'acn ',
        'cyanomethane',
        'acetonitrle',
        'acetonitile',
    ],
    'acetonitrile-d3': [
        'perdeuteronitrile',
        'perdeuteroacetonitrile',
        'perdeutero-acetonitrile',
        'deuteroacetonitrile',
        'd3-acetonitrile',
        'trideuteroacetonitrile',
        'd-acetonitrile',
    ],
    'acetylacetone': [
        'acetyl acetonate',
        'pentane-2,4-dione',
        '2,4-pentanedione',
        'acac',
        'acetyl acetone',
    ],
    'ammonia': [
        'ammonium hydroxide',
        'liquid ammonia',
        'nh3',
        'ammoniacal',
        'ammonia soutions',
    ],
    'anisole': [
        'methoxybenzene',
    ],
    'antimony pentachloride': [
        'sbcl5',
        'pentachloro-antimony',
        'antimony(v) chloride',
    ],
    'antimony pentafluoride': [
        'antimony fluoride',
        'sbf5',
    ],
    'antimony trichloride': [
        'sbcl3',
    ],
    'antimony trifluoride': [
        'sbf3',
    ],
    'benzene': [
        'benzol',
        'benzole',
        'phh',
        'c6h6',
        'benezene',
        'abenzene',
    ],
    'benzene-d6': [
        'deuterobenzene',
        'perdeuterobenzene',
        'hexadeuterobenzene',
        'c6d6',
        'd6-benzene',
        'hexadeutero-benzene',
    ],
    'benzonitrile': [
        'cyanobenzene',
    ],
    'boron trifluoride': [
        'bf3',
    ],
    'bromobenzene': [
        'bromo-perdeuterobenzene',
        'bromoperdeuterobenzene',
        'bromodeuterobenzene',
        '1-bromobenzene',
        'bromo-pentadeuterobenzene',
    ],
    'bromoform': [
        'tribromomethane',
    ],
    'bromomethane': [
        'methyl bromide',
    ],
    'butane': [
        'n-butane',
    ],
    'butyl acetate': [
        'n-butyl acetate',
    ],
    'butylamine': [
        'n-butylamine',
    ],
    'butyric acid': [
        'butanoic acid',
    ],
    'butyronitrile': [
        'n-propyl cyanide',
        'propyl cyanide',
        'butanenitrile',
    ],
    'carbon dioxide': [
        'carbon dioxide gas',
    ],
    'carbon disulfide': [
        'methanedithione',
        'cs2',
    ],
    'carbon tetrachloride': [
        'tetrachloromethane',
        'ccl4',
        'carbontetrachloride',
        'tetrachloride',
    ],
    'carvone': [
        'r-carvone',
        's-carvone',
        'l-carvone',
        'd-carvone',
        '(r)-carvone',
        '(s)-carvone',
    ],
    'chlorobenzene': [
        'chloro-perdeuterobenzene',
        'chloroperdeuterobenzene',
        'phcl',
    ],
    'chloroform': [
        'chlorofochloroform',
        'trichloromethane',
        'tcm',
        'chcl3',
        'chlorofom',
        'chlorofrom',
        'chloroforom',
        'chloform',
        'cf',
        'chlororm',
    ],
    'chloroform-d': [
        'chloroform-d1',
        'chloroform-d6',
        'cdcl3',
        'chcl3-d',
        'trideuterochloroform',
        'deuterochloroform',
        'deutero-chloroform',
        'd-chloroform',
        'deuterated chloroform',
        'perdeuterochloroform',
        'chloroform-d3',
    ],
    'chloromethane': [
        'methyl chloride',
    ],
    'cis-1,2-dichloroethylene': [
        'cis-1,2-dichloroethene',
        'cis-dichloroethene',
    ],
    'collidine': [
        '2,4,6-trimethylpyridine',
        '2,4,6-collidine',
    ],
    'cumene': [
        'isopropylbenzene',
    ],
    'cycloheptane': [
        'cyclo-heptane',
    ],
    'cyclohexane': [
        'cyclo-hexane',
        'cyclohexanes',
        'c-hex',
        'c-hexane',
        'cy-hex',
        'chex',
        'c6h12',
    ],
    'cycloocta-1,5-diene': [
        '1,5-cyclooctadiene',
        'cyclooctadiene',
        '1,5-cod',
    ],
    'cyclooctane': [
        'cyclo-octane',
    ],
    'cyclooctene': [
        'cyclo-octene',
    ],
    'cyclopentane': [
        'cyclo-pentane',
        'cylopentane',
    ],
    'decane': [
        'ndecane',
        'n-decane',
    ],
    'di-t-butyl ether': [
        't-butyl ether',
        'di-tert-butyl ether',
        'dtbe',
    ],
    'diacetone alcohol': [
        '4-hydroxy-4-methylpentane-2-one',
        '4-hydroxy-4-methyl-2-pentanone',
        'diacetone',
    ],
    'dibromomethane': [
        'di-bromomethane',
        'dimromomethane',
    ],
    'dibutyl ether': [
        'di(n-butyl) ether',
        'n-dibutyl ether',
        'n-butyl ether',
        'di-n-buthyl ether',
        'butyl ether',
        'dibutylether',
        'di-n-butyl ether',
    ],
    'dichloroethylene': [
        'dichloroethene',
    ],
    'dichloromethane': [
        'dichoromethane',
        'dicloromethane',
        'dichlormethane',
        'dichlorometahne',
        'dichlormetahne',
        'dichloroemthane',
        'dcm',
        'ch2cl2',
        'methylene chloride',
        'di-chloromethane',
        'dicholomethane',
        'dichloromethane (dichloromethane)',
        'dichlorormethane',
        'methylenechloride',
        'di.chloromethane',
    ],
    'dichloromethane-d2': [
        'dichloro-dideuteromethane',
        'dideuterodichloromethane',
        'dideutero-dichloromethane',
        'cd2cl2',
        'deuterated dichloromethane',
        'deuterodichloromethane',
        'perdeuterodichloromethane',
        'd2-dichloromethane',
        'dichlorodideuteromethane',
    ],
    'dichloromethane/diethyl ether': [
        'ch2cl2:et2o',
    ],
    'diethyl ether': [
        'ethyl ether',
        'ether',
        'et2o',
        'diethylether',
        'ethoxyethane',
        '1-ethoxyethane',
        'dietheyl ether',
        'deithyl ether',
        'diethylrther',
        'diethyl either',
        'ethers',
        'diethyl-ether',
        'diethyloxide',
        'dee',
        'diethyl oxide',
        'dietyl ether',
        'anaerobic ether',
    ],
    'diethyl sulfoxide': [
        'diethylsulfoxide',
        'ethylsulfoxide',
    ],
    'diethylene glycol': [
        'diethyleneglycol',
        'di(ethylene glycol)',
    ],
    'diethylformamide': [
        'dmfa',
        'n,n-diethylformamide',
        'diethyl formamide',
    ],
    'diglyme': [
        'bis(2-methoxyethyl) ether',
        'methyl ether of diethyleneglycol',
        'methyl ether of diethylene glycol',
    ],
    'diiodomethane': [
        'di-iodomethane',
        'diidomethane',
    ],
    'diisopropyl ether': [
        'di-iso-propyl ether',
        'di-i-propyl ether',
        '2-isopropoxypropane',
        '2-propoxypropane',
        'di(isopropyl)ether',
        'di(isopropyl) ether',
        'diisopropylether',
        'di-isopropylether',
        'isopropylether',
        'isopropyl ether',
        'di-isopropyl ether',
        'dipe',
        'di-isopropy ether',
        'di-isopropyl ehter',
        'iso-propylether',
        'iso-propyl ether',
    ],
    'diisopropylbenzene': [
        'di-isopropylbenzene',
        'p-diisopropylbenzene',
    ],
    'dimethoxyethane': [
        '1.2-dimethoxyethane',
        '1,2-dimethoxyethane',
        '1,2-dimethoxy ethane',
        'monoglyme',
        'glyme',
        'dme',
        '1,2-bis(methoxy)ethane',
    ],
    'dimethyl carbonate': [
        'dimethy carbonate',
    ],
    'dimethyl ether': [
        'dimethyl ester',
    ],
    'dimethyl sulfide': [
        'dimethylsulfide',
        'dms',
    ],
    'dimethyl sulfoxide': [
        'dmso',
        'dimethylsulfoxide',
        'dimethylsulphoxide',
        'dimethyl sulphoxide',
        'dimethyl sulfoxide (dimethyl sulfoxide)',
    ],
    'dimethyl sulfoxide-d6': [
        'perdeuterodimethyl sulfoxide',
        'perdeutero-dimethyl sulfoxide',
        'perdeutero-dimethylsulfoxide',
        'd6-dimethyl sulfoxide',
        'hexadeuterodimethylsulfoxide',
        'deuterated dimethylsulfoxide',
        'deuterated dimethyl sulfoxide',
        'hexadeutero dimethyl sulfoxide',
        'hexadeutero-dimethyl sulfoxide',
        'hexadeutero-dimethylsulfoxide',
        'hexadeutero-dmso',
        'd6-dmso',
        'dimethyl sulphoxide d6',
        'dmso d6',
        'dimethyl sulfoxide d6',
        'd-dmso',
    ],
    'dimethylacetamide': [
        'dimethyl acetamide',
        'n,n-dimethylacetamide',
        'dma',
        'dmac',
        "n,n'-dimethylacetamide",
    ],
    'dimethylformamide': [
        'dmf',
        'n,n-dimethylformamide',
        'dimethyl formamide',
        'n,n-dimethyl formamide',
        "n,n'-dimethylformamide",
        'dimethylformamide-methane',
        'dimethylfofmamide',
    ],
    'dimethylformamide-d7': [
        'heptadeutero-dimethylformamide',
        'perdeuterodimethylformamide',
        'dmf-d7',
    ],
    'dipropyl ether': [
        'n-propyl ether',
        'propyl ether',
        'dipropylether',
        'di-n-propyl ether',
    ],
    'dmpu': [
        '1,3-dimethyl-3,4,5,6-tetrahydro-2(1h)-pyrimidinone',
        '1,3-dimethyltetrahydropyrimidinone',
        '1,3-dimethyl-1,3-diazinan-2-one',
        '1,3-dimethyl-3,4,5,6-tetrahydro-2-pyrimidinone',
    ],
    'dodecane': [
        'n-dodecane',
    ],
    'ethanol': [
        'ethyl alcohol',
        'alcohol',
        'rectified spirit',
        'rectified alcohol',
        'etoh',
        'ethanolic',
        'abs. ethanol',
        'absolute ethanol',
        'anhydrous ethanol',
        'ethaethanol',
        'ethano',
        'ethanole',
        'etanol',
        'spirit',
        'methylated spirit',
        'methylated spirits',
        'denatured alcohol',
        'denatured ethanol',
        'ethanol (not dry)',
        'ethanol soution',
        'ethnaol',
    ],
    'ethanol-d6': [
        'deuteroethanol',
        'ethanold6',
    ],
    'ethyl acetate': [
        'ea',
        'acetate',
        'ethylacetate',
        'etac',
        'etoac',
        'acetic ether',
        'ethyl ethanoate',
        'acetyl ethyl ester',
        'diethyl acetate',
        'ethylacetae',
        'ethyl acatate',
        'ethyl actetate',
        'acoet',
        'acoethe',
        'ethyl ester',
        'ethyl-acetate',
        'ethyl ethate',
        'ecatate',
        'eethyl acetate',
        'acetic ester',
    ],
    'ethyl propanoate': [
        'ethyl propionate',
    ],
    'ethylbenzene': [
        'ethyl benzene',
    ],
    'ethylene glycol': [
        'glycol',
        'ethyleneglycol',
    ],
    'ethylenediamine': [
        'ethane-1,2-diamine',
        '1,2-diaminoethane',
    ],
    'fluorinert': [
        'fluorinert fc-43',
        'fluorinert fc-72',
        'fluorinert fc-77',
        'fluorinert fc-84',
        'fluorinert fc-770',
        'fluorinert fc-3283',
        'fc-770',
        'fc-72',
        'fc-77',
        'perfluoroalkyl ether',
        'perfluoroalkyl ethers',
    ],
    'fluorobenzene': [
        'fluoro-perdeuterobenzene',
        'fluoroperdeuterobenzene',
        'phf',
        'fluorophenyl',
    ],
    'formaldehyde': [
        'methanal',
    ],
    'formic acid': [
        'methanoic acid',
    ],
    'gamma-butyrolactone': [
        'butyrolactone',
        'gbl',
    ],
    'heptane': [
        'c7',
        'nheptane',
        'n-heptane',
        'heptanes',
        'hep',
        'h-heptane',
        'i-heptane',
        'n -heptane',
        'n-heptance',
        'isoheptane',
    ],
    'heptanoic acid': [
        'heptaonic acid',
    ],
    'hexadecane': [
        'n-hexadecane',
    ],
    'hexafluorobenzene': [
        'perfluorobenzene',
    ],
    'hexafluoroisopropanol': [
        '1,1,2,2-hexafluoro-2-propanol',
        '1,1,1,3,3,3-hexafluoro-2-propanol',
        'hexafluoropropan-2-ol',
        'hfip',
        'hexafluoro-2-propanol',
        '1,1,1,3,3,3-hexafluoropropan-2-ol',
        '1,1,1,3,3,3-hexafluoroisopropanol',
    ],
    'hexamethyldisilane': [
        'hexamethyldisilicon',
    ],
    'hexamethyldisiloxane': [
        'hmdso',
        'hdmso',
        'hmds',
        'bis(trimethylsilyl) ether',
        'bis(trimethylsilyl)ether',
        'di(trimethylsilyl) ether',
        'di(trimethylsilyl)ether',
        'trimethylsilyl ether',
    ],
    'hexamethylphosphoramide': [
        'hmpa',
    ],
    'hexane': [
        'n-hexane',
        'hexanes',
        'n-hexanes',
        'c6h14',
        'n-c6h14',
        'isohexane',
        'm-hexane',
        'isomeric hexanes',
        'mixed hexanes',
        'skelly b',
        'skelly-b',
        'skelly c',
        'skelly-c',
        'c6',
        'hex',
        'hx',
        'n-hexan',
        'nhexane',
        'isohexanes',
        'i-hexane',
        'n-hexnaes',
        'hexand',
        'n-hxane',
        'n -hexane',
        'h-hexane',
        'haxane',
        'n-exane',
        'iso-hexane',
        'n0hexane',
        '1,2-hexane',
    ],
    'hexanedinitrile': [
        'adiponitrile',
        'hexane-1,6-dinitrile',
    ],
    'hexanoic acid': [
        'hexananoic acid',
    ],
    'hexylene glycol': [
        '2-methyl-2,4-pentanediol',
        'hexyleneglycol',
        'mpd',
    ],
    'hydrazine': [
        'hydrazine hydrate',
    ],
    'hydrobromic acid': [
        'hydrogen bromide',
        'hydrobromic',
        'hbr',
        'hbr aq',
        'hbr aq.',
        'hbr acid',
    ],
    'hydrochloric acid': [
        'hydrochloric',
        'chloridric acid',
        'acido cloridrico',
        'deuterium chloride',
        'hydrogen chloride',
        'hcl',
    ],
    'hydrofluoric acid': [
        'hydrogen fluoride',
        'hf',
        'deuterium fluoride',
        'df',
        'amhydrous hydrogen fluoride',
    ],
    'hydrogen': [
        'hydrogen gas',
    ],
    'hydroiodic acid': [
        'hydroiodide acid',
        'hydrogen iodide',
        'hydriodic acid',
        'hi',
    ],
    'hypophosphorous acid': [
        'hypophosphorous',
        'h3po2',
    ],
    'iodomethane': [
        'methyl iodide',
    ],
    'isoamyl alcohol': [
        '3-methyl-1-butanol',
        'isopentyl alcohol',
        'i-amyl alcohol',
        'iso-pentanol',
        'isopentanol',
    ],
    'isobutanol': [
        '2-methylpropan-1-ol',
        '2-methyl-1-propanol',
        'isobutyl alcohol',
        'iso-butanol',
        'i-buoh',
        'isobutamol',
    ],
    'isooctane': [
        'iso-octane',
        'i-octane',
        '2,2,4-trimethylpentane',
        'trimethylpentane',
    ],
    'isophorone': [
        'isophoron',
    ],
    'isopropyl acetate': [
        'isopropylacetate',
    ],
    'limonene': [
        'l-limonene',
        '(r)-limonene',
        '(s)-limonene',
    ],
    'liquid sulfur dioxide': [
        'liquid so2',
    ],
    'm-cresol': [
        '3-methylphenol',
    ],
    'm-toluenesulfonic acid': [
        'm-toluenesulfonic acid monohydrate',
    ],
    'm-xylene': [
        'meta-xylene',
        '1,3-dimethylbenzene',
        '1,3-xylene',
        'metaxylene',
        'm-xylol',
    ],
    'mesitylene': [
        '2,4,6-trimethylbenzene',
        'mestylene',
        'mestiylene',
        '1,3,5-trimethylbenzene',
    ],
    'methanol': [
        'ch3oh',
        'ch4o',
        'methnol',
        'metanol',
        'meoh',
        'absolute methanol',
        'anhydrous methanol',
        'methanolic',
        'methyl alcohol',
        'methonal',
        'monodeuteromethanol',
        'mono-deuteromethanol',
        'methanol soution',
        'mathanol',
    ],
    'methanol-d4': [
        'deuteromethanol',
        'methanol-d',
        'd4-methanol',
        'deuterated methanol',
        'perdeuteromethanol',
        'tetradeuteromethanol',
        'trideuteromethanol',
        'tetradeutertomethanol',
    ],
    'methyl acetate': [
        'methylacetate',
    ],
    'methyl acetoacetate': [
        'methylacetoacetate',
    ],
    'methyl isobutyl ketone': [
        'mibk',
        '4-methylpentan-2-one',
        '4-methyl-2-pentanone',
        'isobutylmethylketone',
        'methyl-isobutyl-ketone',
        'isobutyl methyl ketone',
    ],
    'methyl perfluorobutyl ether': [
        'methylperfluorobutylether',
        'hfe-7100',
        'novec 7100',
    ],
    'methyl t-butyl ether': [
        't-butyl methyl ether',
        'methyl t-buthyl ether',
        'mtbe',
        'methyl(t-butyl)ether',
        'methyl(tert-butyl)ether',
        'methyl tert-butyl ether',
        'tert-butyl methyl ether',
        't-butylmethyl ether',
        't-butylmethylether',
        't-butylether',
        'methyl-t-butyl ether',
        'methyl-tert-butyl ether',
        '2-methoxy-2-methylpropane',
        'methy(t-butyl)ether',
        'methyl t-butylether',
        'methyltert-butyl ether',
        'methyl-t-butyl-ether',
        'methyl-t-butylether',
        't-butyl-methyl ether',
        'tert-butyl-methyl ether',
        't-butyl(methyl)ether',
        'tert-butyl(methyl)ether',
        'methyl t-butyl ester',
        'methyl t butyl ether',
    ],
    'methylamine': [
        'aminomethane',
    ],
    'methylcyclohexane': [
        'methyl cyclohexane',
        'methycyclohexane',
    ],
    'methylethylbenzene': [
        'methyl-ethylbenzene',
    ],
    'mineral oil': [
        'petrol oil',
        'petroleum oil',
    ],
    'n-ethylpyrrolidone': [
        'nep',
        'n-ethyl-2-pyrrolidone',
        '1-ethyl-2-pyrrolidone',
        '1-ethyl-2-pyrrolidinone',
    ],
    'n-methylformamide': [
        'nmf',
        'n-methyl formamide',
        'n-methyl-formamide',
    ],
    'n-methylpyrrolidone': [
        'nmp',
        'n-methyl-2-pyrrolidone',
        '1-methyl-2-pyrrolidone',
        'n-methyl-2-pyrrolidinone',
        'n-methylpyrrolidinone',
        '1-methylpyrrolidin-2-one',
        'n-methylpyrrolidin-2-one',
        'n-methyl pyrrolidone',
    ],
    'n-propylamine': [
        'propylamine',
    ],
    'nitric acid': [
        'hno3',
    ],
    'nitrobenzene': [
        '1-nitrobenzene',
    ],
    'nitrogen': [
        'dinitrogen',
        'nitrogen gas',
    ],
    'nonane': [
        'n-nonane',
    ],
    'o-cresol': [
        '2-methylphenol',
        'cresol',
    ],
    'o-xylene': [
        'ortho-xylene',
        '1,2-dimethylbenzene',
        '1,2-xylene',
        'orthoxylene',
        'o-xylol',
    ],
    'octane': [
        'c8',
        'noctane',
        'n-octane',
        'n -octane',
        'n-perdeuterooctane',
        'perdeuterooctane',
        'octane-d18',
    ],
    'p-cresol': [
        '4-methylphenol',
    ],
    'p-toluenesulfonic acid': [
        'p- toluenesulfonic acid',
        'para-toluenesulfonic acid',
    ],
    'p-xylene': [
        'para-xylene',
        '1,4-dimethylbenzene',
        '1,4-xylene',
        'paraxylene',
        'p-xylol',
    ],
    'pentamethyldiethylenetriamine': [
        "n,n,n',n',n''-pentamethyldiethylenetriamine",
        'n$1!-[2-(dimethylamino)ethyl]-n$1!,n$2!,n$2!-trimethylethane-1,2-diamine',
        'pmdeta',
    ],
    'pentane': [
        'n-c5h12',
        'c5h12',
        'npentane',
        'n-pentant',
        'pentate',
        'pentante',
        'n-pentane',
        'n-pentanes',
        'c5',
        'pentanes',
        'n -pentane',
        'n-penane',
        'n-pentan',
        'petane',
    ],
    'pentyl acetate': [
        'amyl acetate',
        'n-pentyl acetate',
        'isoamyl acetate',
    ],
    'perchloric acid': [
        'hclo4',
        '0.01 hclo4',
    ],
    'perfluorohexane': [
        'perfluoro-i-hexane',
        'perfluoroisohexane',
        'perfluoro-2-methylpentane',
    ],
    'perfluoromethylcyclohexane': [
        'perfluoro(methylcyclohexane)',
        'pfmc',
    ],
    'petroleum ether': [
        'petrolium ether',
        'peteroleum ether',
        'petroether',
        'petroleum solutions',
        '40-60 petroleum ether',
        '60-80 petroleum ether',
        '60-90 petroleum ether',
        '30-60 petroleum ether',
        'petroleum ether 40-60',
        'petroleum ether 60-80',
        'petroleum ether 60-90',
        'petroleum ether(40-60)',
        '40-60 petrol',
        '60-80 petrol',
        'light petroleum ether',
        'light petroleum 40-60',
        'alkanes',
        'alkane',
        'petroleum',
        'light petroleum',
        'pe',
        'pet',
        'pet ether',
        'petrol',
        'pet. ether',
        'ligroin',
        'petroleum ester',
        'petroleum spirits',
        'petroleum spirit',
        'petrol ether',
        'petrolether',
        'petroleum etther',
        'petrolic ether',
        'petroleum naphtha',
        'benzine',
        'benzin',
        'petroluem ether',
        'light petrol',
        'mineral ether',
        'mineral spirits',
    ],
    'phosphoric acid': [
        'h3po4',
    ],
    'phosphorus oxychloride': [
        'phosphoryl chloride',
    ],
    'polyethylene glycol': [
        'peg400',
        'peg200',
        'peg600',
        'poly(ethylene glycol) 400',
        'poly(ethylene glycol) 200',
        'poly(ethylene glycol) 600',
        'poly(ethylene glycol) 1000',
        'poly(ethylene glycol) 2000',
        'poly(ethylene glycol)',
        'peg 400',
        'peg 200',
        'peg 600',
        'peg-400',
        'peg-200',
        'polyethylene glycol 400',
        'polyethylene glycol 200',
        'polyethylene glycol 600',
        'polyethylene glycol 1000',
        'polyethylene glycol 2000',
        'poly(ethylene glycol)dimethyl ether',
        'polyethylene glycol dimethyl ether',
        'pegdme',
    ],
    'polypropylene glycol': [
        'poly(propyleneglycol)',
        'poly(propylene glycol)',
        'ppg',
    ],
    'propionic acid': [
        'propanoic acid',
    ],
    'propionitrile': [
        'etcn',
        'prcn',
        'ethyl cyanide',
        'propanenitrile',
        'propiononitrile',
        'c2h5cn',
    ],
    'propylene carbonate': [
        '4-methyl-1,3-dioxolan-2-one',
    ],
    'propylene glycol': [
        '2-hydroxypropan-1-ol',
        'propanediol',
        '1,2-propanediol',
    ],
    'silicone oil': [
        'polydimethylsiloxane',
        'pdms',
    ],
    'sulfur dioxide': [
        'so2',
        'dioxo-sulfane',
        'dioxidosulfur',
        'sulphur dioxide',
    ],
    'sulfuric acid': [
        'h2so4',
        'sulphuric acid',
    ],
    'sulfuryl chloride fluoride': [
        'so2clf',
        'chloro(fluoro)sulfone',
        'chlorofluorosulfone',
        'fluorosulfuryl chloride',
    ],
    'sulfuryl fluoride': [
        'so2f2',
    ],
    't-butanol': [
        '2-methylpropan-2-ol',
        'tert-butyl alcohol',
        'tert-butanol',
        't-butyl alcohol',
        't-buoh',
        'tbuoh',
    ],
    't-butylamine': [
        'tert-butylamine',
        'tert-butyl amine',
        't-butyl amine',
        '2-methylpropan-2-amine',
    ],
    'tetrachloroethylene': [
        'tetrachloroethene',
        'perchloroethylene',
        'perchloroethene',
        'pce',
    ],
    'tetradecane': [
        'n-tetradecane',
    ],
    'tetraethylurea': [
        '1,1,3,3-tetraethylurea',
        'tetra-n-ethylurea',
        'tetraethyl urea',
        'n,n,n,n-tetraethylurea',
    ],
    'tetrahydrofuran': [
        'thf',
        'oxolane',
        'tetrahydrofurane',
        'tetrahydrofuan',
        'tetrahydrofurthorium',
        'tetrahydrofuram',
        'tetrahydrofurán',
        'tetrahydrofuran (tetrahydrofuran)',
        'form saturated tetrahydrofuran',
        'tetrahydrufurane',
        'tetrahydrufuran',
    ],
    'tetrahydrofuran-d8': [
        'd8-tetrahydrofuran',
        'perdeuterotetrahydrofuran',
        'octadeuterofuran',
        'octadeuterotetrahydrofuran',
        'd-thf',
    ],
    'tetrahydropyran': [
        'thp',
        'tetrahydro-2h-pyran',
        'oxane',
    ],
    'tetramethylethylenediamine': [
        "n,n,n',n'-tetramethylethane-1,2-diamine",
        "n,n,n',n'-tetramethylethylenediamine",
        'tmeda',
        'tetramethyldiaminoethane',
        'n,n,n,n-tetramethylethylenediamine',
        'n$1!,n$1!,n$2!,n$2!-tetramethylethane-1,2-diamine',
        'temed',
        "n,n,n',n'-tetramethylethylendiamine",
        'n,n,n′,n′-tetramethylethylenediamine',
        '1,1,4,4-tetra-methyl-ethylenediamine',
        '1,1,4,4-tetramethylethylenediamine',
    ],
    'tetramethylsilane': [
        'tms',
        'tetramethysilane',
        'si(ch3)4',
    ],
    'tetramethylurea': [
        '1,1,3,3-tetramethylurea',
        'tetramethyl urea',
    ],
    'thionyl chloride': [
        'socl2',
        'dichlorosulfoxide',
        'dichlorooxidosulfur',
    ],
    'titanium tetrachloride': [
        'ticl4',
    ],
    'toluene': [
        'toulene',
        'tol',
        'tolune',
        'phme',
        'toluol',
        'p-toluol',
        'n-toluene',
        'methylbenzene',
        'tolouene',
        'toleuene',
    ],
    'toluene-d8': [
        'perdeuterotoluene',
        'd8-toluene',
        'deuterotoluene',
        'deuterated toluene',
    ],
    'trans-1,2-dichloroethylene': [
        'trans-1,2-dichloroethene',
        'trans-dichloroethene',
    ],
    'trichloroethylene': [
        'trichloroethene',
        '1,1,2-trichloroethene',
        'tce',
    ],
    'triethylamine': [
        'et3n',
        'net3',
        'tea',
    ],
    'triethylene glycol': [
        'triethyleneglycol',
    ],
    'triethylorthoformate': [
        'triethylformate',
        'triethyl orthoformate',
        'ethyl orthoformate',
        'diethylorthoformate',
        'triethyl orthorformate',
    ],
    'trifluoroacetic acid': [
        'trifluroracetic acid',
        'trifluoroacetic',
        'tfa',
    ],
    'trifluoromethanesulfonic acid': [
        'triflic acid',
    ],
    'trifluoromethylbenzene': [
        '(trifluoromethyl)benzene',
        'trifluorotoluene',
        'phcf3',
        'alpha,alpha,alpha-trifluorotoluene',
        'btf',
    ],
    'trimethylacetonitrile': [
        't-butylcyanide',
        'tert-butylcyanide',
        'pivalonitrile',
        '2,2-dimethylpropanenitrile',
    ],
    'trimethylamine': [
        'n,n-dimethylmethanamine',
    ],
    'trimethylorthoformate': [
        'trimethylformate',
        'trimethyl orthoformate',
        'methyl orthoformate',
        'trimethoxymethane',
    ],
    'undecane': [
        'n-undecane',
    ],
    'valeric acid': [
        'pentanoic acid',
    ],
    'vanadium tetrachloride': [
        'vcl4',
        'vanaduim tetrachloride',
    ],
    'water': [
        'hplc water',
        'millipore water',
        'milli-q water',
        'milli-q',
        'naclaq',
        'p123 aqueous',
        'lc-ms water',
        'hydrogen tetrafluoroborate',
        'tetrafluoroboric acid',
        'hbf4',
        '(water) drying',
        'nh4oh',
        'h2o',
        'aqueous',
        'aq',
        'aq.',
        'nacl',
        'kcl',
        'koh',
        'naoh',
        'sodium carbonate',
        'potassium carbonate',
        'sodium bicarbonate',
        'sodium hydroxide',
        'potassium hydroxide',
        'sodium chloride',
        'sodium acetate',
        'ammonium acetate',
        'ammonium chloride',
        'lioH',
        'oxygen-free aqueous',
        'deoxygenated water',
        'degassed water',
        'saturated aqueous solution',
        'saturated aqueous',
        'aqueous solution',
        'aqueous buffer',
        'aqueous medium',
        'phosphate buffer',
        'acetate buffer',
        'citrate buffer',
        'buffer',
        'aqueous phase',
        'from water',
        'distilled water',
        'dw',
        '1 droplet of water',
        'a drop of water',
        'a few drops of water',
        'drops of water',
        'drop of water',
        'deionised water',
        'de-ionised water',
        'deionized water',
        'de-ionized water',
        'double distilled water',
        'doubly distilled water',
        'demineralised water',
        'demineralized water',
        'de-mineralised water',
        'double-distilled water',
        'triple-distilled water',
        'triple distilled water',
        'saline',
        'normal saline',
        'physiological saline',
        'perchlorate buffer',
        'phosphate buffer saline',
        'saline buffer',
    ],
    'water-d2': [
        'deuterium oxide',
        'd2o',
        'heavy water',
        'dideuterated water',
        'dideuterium oxide',
        'phosphate-buffered deuterium oxide',
        'ph 7 10 mm phosphate-buffered deuterium oxide',
    ],
    'xylene': [
        'xylenes',
        'xylol',
    ],
}

# Variantes/typos d'additifs non-solvants (sels, acides amines, reactifs...)
# -> None : ignores silencieusement, pas de forme canonique associee.
NON_SOLVENT_SYNONYMS = [
    '-1-amino-2-(methoxymethyl)pyrrolidone',
    '1 ua',
    '1,1,1,3,3,3-hexafluoropropane',
    '1,1-cyclohexanediacetic acid',
    '1,2-dibromopropane',
    '1,3,5-trihydroxybenzene',
    '1,3,5-trinitrobenzene',
    '1,3,5-tris(propan-2-yl)benzene',
    '1,3-dibromopropane',
    '1,3-dimethylbarbituric acid',
    '1,3-diphenylpropan-2-one',
    '1,4-hydroxybenzene',
    '1,5-diazabicyclo[4.3.0]non-5-ene',
    '1,5-dibromopentane',
    '1,8-diazabicyclo[5.4.0]undec-7-ene',
    '1-amino-2-(methoxymethyl)pyrrolidine',
    '1-amino-2-(methoxymethyl)pyrrolidone',
    '1-azidohexane',
    '1-butyl-1-methylpyrrolidinium triflate',
    '1-chloro-2,4-dinitrobenzene',
    '1-naphthol',
    '1-phenyl-1-propyne',
    '1-phenylethylamine',
    '12-crown-4',
    '15-crown-5',
    '18-crown-6',
    '2 ua',
    "2,2'-biphenol",
    "2,2'-bipyridine",
    "2,2'-bipyridyl",
    '2,2-dimethylbutanoic acid',
    '2,3-dichloro-5,6-dicyano-1,4-benzoquinone',
    '2,5-dimethylpyrrole',
    '2,6-dimethylaniline',
    '2-bromophenol',
    '2-butylmercaptan',
    '2-chloropyrazine',
    '2-formylpyridine',
    '2-naphthol',
    '2-phenylpyridine',
    '2-picolylamine',
    '3-bromophenol',
    '3-formylpyridine',
    '3-phenylpyridine',
    '3-picolylamine',
    "4,4'-bipyridine",
    "4,4'-bipyridyl",
    '4-bromophenol',
    '4-chlorophenol',
    '4-fluorophenol',
    '4-formyl-2,6-lutidine',
    '4-formylpyridine',
    '4-phenylpyridine',
    '4-picolylamine',
    '6-carbethoxy-2,2,6-trimethylcyclohexanone',
    '[bmim][tf2]',
    '[bmim]bf4',
    '[bmim]clo4',
    '[bmim]ntf2',
    '[bmim]pf6',
    '[bmim]tf2',
    '[emim]bf4',
    '[emim]clo4',
    '[emim]ntf2',
    '[emim]pf6',
    'activated',
    'actol',
    'adamantane amine hydroiodide',
    'adenosine',
    'adipic acid',
    'alcoholic potassium hydroxide',
    'alcoholic solution',
    'alpha-naphthol',
    'ambient conditions',
    'ammonium bromide',
    'ammonium phosphate',
    'ammonium sulfate',
    'aqua regia',
    'aqueous alcohols',
    'asparagine',
    'at cryogenic temp',
    'at cryogenic temperature',
    'barbituric acid',
    'benzene sulfonic acid',
    'benzenesulfonic acid',
    'benzenesulphonic acid',
    'benzhydryl chloride',
    'benzhydrylchloride',
    'benzo-18-crown-6',
    'benzoyl acetone',
    'benzoyl peroxide',
    'beta-naphthol',
    'betainium bistriflimide',
    'bipyridine',
    'bipyridyl',
    'boiling',
    'boric acid',
    'butyl-methylimidazolium tetrafluoroborate',
    'butyric anhydride',
    'c2h2cn',
    'caesium acetate',
    'caesium chloride',
    'caesium nitrate',
    'calcium perchlorate',
    'carbon monooxide',
    'carbon monoxide',
    'carborane',
    'catechol',
    'cesium acetate',
    'cesium chloride',
    'cesium nitrate',
    'cf3coph',
    'chicoric acid',
    'chlorogenic acid',
    'chromium chloride',
    'cis',
    'cis,cis-muconic acid',
    'cis,trans-muconic acid',
    'cis-2-pentenenitrile',
    'cis-muconic acid',
    'clear',
    'cobalt chloride',
    'cof-300-dc',
    'colorless',
    'colourless',
    'copper acetate',
    'copper chloride',
    'copper dinitrate',
    'copper sulfate',
    'crystal mount',
    'crystal mounting',
    'crystallised',
    'crystallized',
    'csoac',
    'curcumin',
    'cyanogen',
    'cyclooctylamine',
    'cytidine',
    'd-asparagine',
    'd-leucine',
    'd-proline',
    'd-tartaric acid',
    'dark',
    'darkness',
    'dbn',
    'dbu',
    'ddq',
    'deet',
    'deta',
    'di-cesium sulfate',
    'di-t-butylperoxide',
    'diacetylic',
    'dibenzo-18-crown-6',
    'dibenzyl ketone',
    'dibromopentane',
    'dichloro-zinc',
    'dicyclohexylamine',
    'diet',
    'diethyl squarate',
    'diethylenetriamine',
    'dihydrate',
    'dihydrogen phosphate',
    'diisopropylethylamine',
    'dimethyl fluoride',
    'dipea',
    'direct isolation',
    'dl-tartaric acid',
    'dmmf',
    'dry air',
    'edit',
    'ethanethiol',
    'ethyl',
    'ethyl 2-oxocyclohexanecarboxylate',
    'ethyl triflate',
    'ethyl-2-oxocyclohexanecarboxylate',
    'ethylene',
    'etosc',
    'fecl3',
    'ferrocene',
    'fill',
    'freezing',
    'glycine',
    'guanosine',
    'h3po3',
    'heptahydrate',
    'hexachlorocyclopentadiene',
    'hexahydrate',
    'hexamethylbenzene',
    'high temperature',
    'humid air',
    'hunig base',
    "hunig's base",
    'hydrate',
    'hydrocinnamic acid',
    'hydrogen phosphate',
    'hydroquinone',
    'hydroxide',
    'hypophosphoric acid',
    "hünig's base",
    'imidazolidine-2-thione',
    'indole',
    'iron chloride',
    'iron sulfate',
    'isonicotinamide',
    'isophthalic acid',
    'jviospdfgvlsae',
    'khco3',
    'l-alanine',
    'l-arginine',
    'l-asparagine',
    'l-aspartic acid',
    'l-cysteine',
    'l-glutamic acid',
    'l-glutamine',
    'l-glycine',
    'l-histidine',
    'l-isoleucine',
    'l-leucine',
    'l-lysine',
    'l-methionine',
    'l-nicotine',
    'l-phenylalanine',
    'l-proline',
    'l-serine',
    'l-tartaric acid',
    'l-threonine',
    'l-tryptophan',
    'l-tyrosine',
    'l-valine',
    'leucine',
    'leyering',
    'lithium bis(trifluoromethanesulfonyl)imide',
    'lithium chloride',
    'lithium perchlorate',
    'lithium triflate',
    'low temperature',
    'm-bromophenol',
    'm-carborane',
    'magnesium perchlorate',
    'melting',
    'methane',
    'methanethiol',
    'methyl propiolate',
    'methyl tosylate',
    'methyl triflate',
    'methylhydrazine',
    'methyltriflate',
    'moist air',
    'monohydrate',
    'muconic acid',
    "n,n'-diphenylformamidine",
    'n,n-diethyl-m-toluamide',
    'n,n-diethyl-meta-toluamide',
    'n,n-diisopropylethylamine',
    'n-methyl urea',
    'na',
    'nabf4',
    'naclo4',
    'naotf',
    'nbu4nbf4',
    'nh4pf6',
    'nickel chloride',
    'nicotine',
    'nitrile',
    'no(g)',
    'nonahydrate',
    'o-bromophenol',
    'o-carborane',
    'one-pot',
    'onepot',
    'p-bromophenol',
    'p-carborane',
    'p123',
    'pentaerythritol',
    'pentafluorophenol',
    'pentahydrate',
    'pentanoic anhydride',
    'pet polymer',
    'phenylethanal',
    'phenylethylamine',
    'phenylsilane',
    'phloroglucinol',
    'phosphate',
    'phosphorus pentachloride',
    'phosphorus tribromide',
    'phosphorus trichloride',
    'piperazine',
    'poly(methyl methacrylate)',
    'poly(vinylpyrrolidone)',
    'polyethylene',
    'polyethylene polyamines',
    'polyethylene terephthalate',
    'polymethylmethacrylate',
    'polystyrene',
    'polyvinylpyrrolidone',
    'potassium bromide',
    'potassium ethoxide',
    'potassium hexafluorophosphate',
    'potassium iodide',
    'potassium methoxide',
    'potassium nitrate',
    'potassium phosphate',
    'potassium sulfate',
    'potassium t-butoxide',
    'propionic anhydride',
    'propylene',
    'pvp',
    'pvp k17',
    'pvp k30',
    'pvp k90',
    'pyridinium p-toluenesulfonate',
    'pyrroline',
    'reaction',
    'recrystallisation',
    'recrystallization',
    'resorcinol',
    'room conditions',
    'room temperature',
    'rt',
    'sebacic acid',
    'sefe',
    'simulated body fluid',
    'simulated gastric fluid',
    'simulated intestinal fluid',
    'sodium ethoxide',
    'sodium hexafluorophosphate',
    'sodium iodide',
    'sodium methoxide',
    'sodium nitrate',
    'sodium p-nitrobenzoate',
    'sodium perchlorate',
    'sodium phosphate',
    'sodium sulfate',
    'sodium t-butoxide',
    'sodium tetrasulfide',
    'sodium triflate',
    'sodium trifluoromethane sulfonate',
    'solv evap',
    'solvent',
    'suberic acid',
    'sublimation',
    'sublimes',
    'succinic acid',
    'sulfonic acid',
    't-butylperoxide',
    'tartaric acid',
    'tbabf4',
    'tbaf',
    'tbapf6',
    'tcnq',
    'terephthalic acid',
    'tetra-n-butylammonium fluoride',
    'tetra-n-butylammonium fluoride trihydrate',
    'tetrabutylammonium bromide',
    'tetrabutylammonium chloride',
    'tetrabutylammonium fluoride',
    'tetrabutylammonium hexafluorophosphate',
    'tetrabutylammonium perchlorate',
    'tetrabutylammonium tetrafluoroborate',
    'tetracyanoquinodimethane',
    'tetraethylammonium bromide',
    'tetraethylammonium chloride',
    'tetraethylammonium hexafluorophosphate',
    'tetraethylammonium perchlorate',
    'tetraethylammonium tetrafluoroborate',
    'tetrafluoroethylene',
    'tetrahydrate',
    'tetraisopropylcyclopentadiene',
    'tetramethylammonium bromide',
    'tetramethylammonium chloride',
    'tetramethylammonium hexafluorophosphate',
    'thioacetamide',
    'thiourea',
    'thymidine',
    'trans',
    'trans,trans-muconic acid',
    'trans-muconic acid',
    'transparent',
    'tri-n-propylphosphine',
    'tributylphosphine',
    'triethylborane',
    'triethylgallium',
    'triethylsilane',
    'trifluoroacetic acid anhydride',
    'trifluoromethyl',
    'trihydrate',
    'trimesic acid',
    'trimethylgallium',
    'trimethylphosphine',
    'trimethylsilane',
    'trimethylsilyl chloride',
    'triphenylacetic acid',
    'triphenylarsine',
    'triphenylphosphine',
    'triphenylphosphine oxide',
    'triphenylphosphine sulfide',
    'tripropylphosphine',
    'tris',
    'tris(pyrrolidino)phosphine oxide',
    'tris-buffer',
    'tris-hcl',
    'vanadium oxytrichloride',
    'zinc chloride',
    'zinc dichloride',
]

# Dict plat genere a partir des deux structures ci-dessus (c'est lui qu'utilise
# parse_solvent.py). Toutes les cles sont en minuscules.
SYNONYMS = {}
for _canonical, _variants in SYNONYM_GROUPS.items():
    for _v in _variants:
        if _v in SYNONYMS and SYNONYMS[_v] != _canonical:
            raise ValueError(f'synonyme en conflit {_v!r} : {SYNONYMS[_v]!r} vs {_canonical!r}')
        SYNONYMS[_v] = _canonical
for _v in NON_SOLVENT_SYNONYMS:
    SYNONYMS[_v] = None
del _canonical, _variants, _v

# ── NON-SOLVANTS → None sans stop ─────────────────────────────────────────────
# Méthodes de cristallisation qui ne sont PAS des solvants.
NON_SOLVENT_KW = (
    'hydrothermal',
    'solvothermal',
    'solvo-thermal',
    'solvent-thermal',
    'solvothermic',
    'solventhermal',
    'solvent-free',
    'solventless',
    'microwave',
    'accelerated ageing',
    'accelerated aging',
    'diffussion',
    'solvothemal',
    'cooperative phase',
    'phase transition',
    'inverse temeprature',
    'inverse temperature crystallization',
    'inverse temperature crystallisation',
    'weak crystallinity',
    'weak crystal',
    'vapour deposition',
    'vapor deposition',
    'molecular beam deposition',
    'beam deposition',
    'physical deposition',
    'sublimation',
    'sublimed',
    'vacuum distillation',
    'distillation',
    'solid state',
    'mechanochemical',
    'in-situ',
    'in situ grown',
    'melt crystalliz',
    'melt grown',
    'nature sample',
    'electrocrystalli',
    'from the melt',
    'thermal solid',
    'solid-state',
    'solid state',
    'thermal treatment',
    'grinding',
    'ball mill',
    'mechanosynthesis',
    'thermal annealing',
    'desolvation',
    'dehydration',
    'freeze-dry',
    'freeze dry',
    'lyophili',
    'soaking',
    'sorption',
    'wet chemistry',
    'solvent exchange',
    'guest exchange',
    'single crystal to',
    'single-crystal',
    'sc to sc',
    'scsc',
    'sc-sc',
    'atmospheric moisture',
    'moisture replacement',
    'in a dac',
    'dac crystallis',
    'dac crystalliz',
    'diamond anvil',
    'crystallised in a',
    'crystallized in a',
    'crystallisation in',
    'crystallization in',
    'in situ crystalliz',
    'grown in',
    'grown by',
    'capillary',
    'vapour diffusion',
    'vapor diffusion',
    'slow diffusion',
    'diffusion method',
    'solvent diffusion',
    'liquid diffusion',
    'slow cooling',
    'cooling method',
    'crash cooling',
    'solution diffusion',
    'solution layering',
    'solvent layering',
    'solvent evaporation',
    'evaporative crystalliz',
    'evaporative crystallis',
    'room temperature',
    'layering',
    'used as rec',
    'used as supplied',
    'as supplied',
    'as received',
    'as made',
    'as-made',
    'activation',
    'obtained',
    'see esi',
    'see supporting',
    'see si',
    'see supplementary',
    'solvent volatilization',
    'slow volatilization',
    'method',
    'evaporation',
    'cooling',
    'diffusion',
    'precipitation',
    'recrystallization',
    'recrystallisation',
    'crystalization',
    'crystalisation',
    'slow evporation',
    'slow evapoaration',
    'slow evaopration',
    'slow evpaporation',
    ' in-',
    'solvothermo',
    'solvethermal',
    'solventthermal',
    'low temperature',
    'high temperature',
    'dropwise',
    'spray drying',
    'spray-drying',
    'polar protic',
    'polar aprotic',
    'hydration',
    'evoparation',
    'ionothermal',
    'gel',
    'gel crystallization',
    'gel crystallisation',
    'mother liquor',
    'liquor mother',
    'mother solution',
    'filtrate',
    'growth',
    'exchange',
    'situ',
    'technique',
    'mof',
    'photolytic',
    'contact reaction',
    'reaction mixture',
    'reaction solution',
    'reaction media',
    'reaction medium',
    'during reaction',
    'during synthesis',
    'crude',
    'powder',
    'block',
    'plate',
    'needle',
    'prism',
    'rod',
    'octahedron',
    'octahedral',
    'cubic',
    'tetrahedron',
    'rhombus',
    'lath',
    'flake',
    'pillar',
    'commercial',
    'natural',
    'nature',
    'camphor sulfonate',
    'crystal from capsule',
    'single crystal',
    'crystal sponge',
    'crystalline sponge',
    'sponge method',
    'electrochemical',
    'electrocrystallization',
    'electro-crystallization',
    'electrolysis',
    'electrochemical oxidation',
    'electrical oxidation',
    'thermal gradient',
    'inverse temperature crystallization',
    'inverse temperature crystallisation',
    'organic solvent',
    'inorganic solvent',
    'mixed solvent',
    'mild solution approach',
    'solution approach',
    'solution crystallization',
    'solution crystallisation',
    'mixing reactants',
    'upon mixing',
    'model urine',
    'urine',
    'blood',
    'plasma',
    'serum',
    'hanging drop',
    'sitting drop',
    'microbatch',
    'microcrystalliz',
    'high throughput',
    'high-throughput',
    'enact protocol',
    'enact technique',
    'crystal prepared',
    'mosquito',
    'via the',
    'protocol',
    'process',
    'screening',
    'immersion in liquid nitrogen',
    'liquid nitrogen',
    'in situ',
    'vapor phase',
    'vapour phase',
    'vapor',
    'vapour',
    'physical vapor',
    'physical vapour',
    'gas phase',
    'laser',
    'high entropy',
    'slurry',
    'precursor solution',
    'high pressure',
    'high-pressure',
    'glovebox',
    'glove box',
    'storage of',
    'storage',
    'removal from solvated',
    'solvated crystals',
    'after coloration',
    'sonochemical',
    'solvent-assisted ligand exchange',
    'ligand exchange',
    'ionic liquid synthesis',
    'concentration gradient',
    'decomposition',
    'penetration',
    'standing at',
    'encapsulated nanodroplet',
    'encapsulated nano-droplet',
    'encapsulated nano droplet',
    'crystalline sponge',
    'antisolvent',
    'anti-solvent',
    'supercritical',
    'flux',
    'the melt',
    'from melt',
    'melt',
    # lumière ambiante (condition, pas solvant)
    'ambient light',
    # température ambiante standalone
    'at room temp',
    # systèmes cristallins (descriptions crystallographiques, pas solvants)
    'monoclinic',
    'orthorhombic',
    'triclinic',
    'hexagonal',
    'tetragonal',
    'trigonal',
    'rhombohedral',
    'diffraction',
    'well diifraction',
    'volatile crystallization',
    'volatile crystallisation',
    'zone refinement',
    'zone refin',
    'directly from solution',
    'corrosion deposit',
    'crash cooled',
    'structural change',
    'induced structural',
    'oil state',
    'double layer',
    'crystaliisation',
    'crystaliization',
    'thermal stress',
    'amorphous molten',
    'molten phase',
    'volatilize',
    'volatilisation',
    'volatilization',
    'reconstituted',
    'antibacterial',
    'seed',
    'hydrothemal',
    'crystallisation',
    'crystallization',
    'precipitate',
    'stacking',
    # cristallisation assistée par champ électrique
    'electric field',
    # procédés thermiques / techniques cristallo
    'annealing',
    'aerobic oxidation',
    'aerobic',
    'photocrystallography',
    'photocrystall',
    # conditions de pression (GPa, MPa, bar)
    'gpa',
    'mpa',
    # descriptions de procédé
    'freezing the',
    'liquid sample',
    # typos de méthodes (pas solvants)
    'exchnage',
    'evpouration',
    'evpouration',
    # méthode de croissance à l'interface
    'interface growth',
    'interface crystalliz',
    'interface crystallis',
    'postcrystallised',
    'postcrystallized',
    'ionic self assembly',
    'self-assembly',
    'granulation',
    'wet granulation',
    'dry granulation',
    'ultrasonication',
    'sonication',
)

# ── PRÉFIXES MÉTHODE → retirés avant analyse ─────────────────────────────────
# Du plus long au plus court (ordre garanti par sorted).
METHOD_PREFIXES = sorted((
    're-crystallisation from solvent:',
    're-crystallization from solvent:',
    'recrystallisation from solvent:',
    'recrystallization from solvent:',
    'the material was recrystallised from a mixture of',
    'the material was recrystallized from a mixture of',
    'crystallised from a mixture of',
    'crystallized from a mixture of',
    'recrystallised from a mixture of',
    'recrystallized from a mixture of',
    'crystalised from a mixture of',
    'crystalized from a mixture of',
    'from a molar mixture of',
    'from a mixture of',
    'from mixture of',
    'molar mixture of',
    'mixture of',
    'ratio of',
    'mix of',
    'mix solvent of',
    'mixture ',
    'the material was recrystallised from',
    'the material was recrystallized from',
    'the material was recrystallised by',
    'the material was recrystallized by',
    'recrysatallisation from',
    'recrysatallization from',
    'recrystallises from',
    'recrystallizes from',
    'recrystallised from',
    'recrystallized from',
    'recrystallisation from',
    'recrystallization from',
    're-crystallisation from',
    're-crystallization from',
    'crystalised from',
    'crystalissed from',
    'crystalized from',
    'crystalllization from',
    'crystalllisation from',
    'crystallised from',
    'crystallized from',
    'crystallized fom',
    'crystallzed from',
    'crystallsied from',
    'crystallisation form',
    'crystallization form',
    'crystalized from',
    'crystallization from',
    'crystallisation from',
    'isothermic crystallization from',
    'isothermal crystallization from',
    'isothermic crystallisation from',
    'isothermal crystallisation from',
    'isotermic crystallization from',
    'isotermal crystallization from',
    'isotermic crystallisation from',
    'isotermal crystallisation from',
    'carbon monoxide saturated ',
    'carbon monooxide saturated ',
    'carbon monoxide purged ',
    'nitrogen purged ',
    'argon purged ',
    'oxygen free ',
    'lt crystallisation from',
    'lt crystallization from',
    'rt crystallisation from',
    'rt crystallization from',
    'ht crystallisation from',
    'ht crystallization from',
    'lt crystallisation',
    'lt crystallization',
    'rt crystallisation',
    'rt crystallization',
    'ht crystallisation',
    'ht crystallization',
    'slowly crystallized from',
    'slowly crystallised from',
    'recrysallised from',
    'recrysalized from',
    'recryszallization from',
    'recryszallisation from',
    'recristallisation from',
    'recristallization from',
    'recristallisation',
    'recristallization',
    'crystallised form',
    'crystallized form',
    'slow crystallization from an',
    'slow crystallization from',
    'slow crystallisation from an',
    'slow crystallisation from',
    'fractional crystallization from',
    'fractional crystallisation from',
    'fractional crystallization of',
    'fractional crystallisation of',
    'slow cooleing of a',
    'slow addition of',
    'slow cooleing of',
    'slow cooleing from',
    'slow cooling from',
    'slow cool from',
    'slowly cooled from',
    'slow-cooled from',
    'slowly cooled in',
    'slow cool of',
    'cooled from',
    'cooled in',
    'cooled to',
    'slow evaporation of the',
    'slow evaporation from a',
    'slow evap from',
    'slow evap of',
    'slow evap',
    'crystallisation from a',
    'crystallization from a',
    'crystallised out of',
    'crystallized out of',
    'crystallised by',
    'crystallized by',
    'crystallised from a',
    'crystallized from a',
    'evaporation of a mixture of',
    'evap of mixture of',
    'evap of',
    'evaporation of',
    'using',
    'in ',
    'from',
    'aus ',
    'double decomposition in',
    'double decomposition',
    'reactive crystallization in',
    'reactive crystallisation in',
    'reactive crystallization',
    'reactive crystallisation',
    'water assisted',
    'from an',
    'from a',
    'slow evaporation from',
    'slow evaporation of a',
    'slow evaporation of',
    'slow evaporation in',
    'slow evaporation',
    'solvent system:',
    'solvents:',
    'solvent:',
    'solvent ',
    'solution ',
    'solutions of',
    'solutions ',
    'soluiton of',
    'soluiton ',
    'layered solvent',
    'including',
    'concentration of',
    'concentration ',
    'carbon dioxide expanded',
    'antisolvent',
    'anti-solvent',
    'co-crystallisation from',
    'co-crystallization from',
    'co-crystallisation by',
    'co-crystallization by',
    'co-crystallisation',
    'co-crystallization',
    'co-crystalisation from',
    'co-crystalization from',
    'co-crystalisation',
    'co-crystalization',
    'crystals grown from',
    'crystals grown in',
    'crystal grown from',
    'crystal grown in',
    'isolated from',
    'isolated in',
    'out of',
    'obtained from',
    'obtained in',
    'prepared from',
    'prepared in',
    'dissolved in',
    'grown from',
    'grown in',
    'a ',
    'an ',
    'the ',
), key=len, reverse=True)

# ── MOTS-CLÉS DESCRIPTION (après retrait des préfixes) → None sans stop ───────
DESCRIPTION_KW = (
    'crystals were',
    'crystal was',
    'was crystallized',
    'was crystallised',
    'was recrystallized',
    'was recrystallised',
    'recrystallized',
    'recrystallised',
    'was obtained',
    'was isolated',
    'collected from same',
    'collected from',
    'heating of',
    'by heating',
    'crystallizes spontaneously',
    'spontaneously from',
    'used at received',
    'received from',
    'as received',
    'nmr tube',
    'nmr-tube',
    'exchanged from',
    'solvent exchange',
    'solution was',
    'was left',
    'was allowed',
    'was dissolved',
    'was added',
    'was heated',
    'solution of',
    'obtained by',
    'obtained at',
    'grown by',
    'produced by',
    'synthesis',
    'diffusion of',
    'atmosphere of',
    'atmosphere:',
    'slowly evapor',
    ' above ',
    ' by exchange',
    'atmospheric',
    ' into ',
    ' with ',
    ' under ',
    ' in ',
    ' then ',
    'layered with',
    'layered on',
    'layering ',
    'diffused into',
    'diffusing into',
    'vapour diffusion',
    'vapor diffusion',
    'pentane into',
    'ether into',
    'hexane into',
    'diethyl ether into',
    'by waiting',
    'by standing',
    'by leaving',
    'on standing',
    'on cooling',
    'oil crystallised',
    'oil crystallized',
    'by addition',
    'crystals formed',
    'crystallized while',
    'crystallised while',
    'growth technique',
    'solution growth',
    'cork of wine bottle',
    'cork of',
)
